server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.53.54:3306/examination_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 7181232
  redis:
    host: 47.100.53.54
    password: ''
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    port: 6379
mybatis-plus:
  mapper-locations:  classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      capital-mode: false
      table-underline: false