server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.53.54:3306/examination_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 7181232
  redis:
    host: 47.100.53.54
    password: ''
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    port: 6379
mybatis-plus:
  mapper-locations:  classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      capital-mode: false
      table-underline: false